### PR TITLE
Add support for OTP24

### PR DESCRIPTION
**Pull request by hidnasio**
## Description of the change

> OTP23 deprecated the old crypto API and OTP24 removed it. This PR updates the code to use the new crypto API to make it compatible with OTP24. More info here http://erlang.org/doc/apps/crypto/new_api.html

> Requires Elixir 1.12 https://hexdocs.pm/elixir/1.12/compatibility-and-deprecations.html#compatibility-between-elixir-and-erlang-otp

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change
- [ ] Technical Debt
- [ ] Documentation

## Related tickets

> https://app.shortcut.com/active-prospect/story/16538/upgrade-elixir-apps-to-the-latest-versions

### Development and Testing

- [x]  Lint rules pass locally.
- [x]  The code changed/added as part of this pull request has been covered with tests, or this PR does not alter production code.
- [x]  All tests related to the changed code pass in development, or tests are not applicable.

### Code Review

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached.
- [ ]  At least two engineers have been added as "Reviewers" on the pull request.
- [ ]  Changes have been reviewed by at least two other engineers who did not write the code.
- [ ]  This branch has been rebased off master to be current.

### Tracking 
- [x]  Issue from Clubhouse has a link to this pull request.
- [x]  This PR has a link to the issue in Clubhouse.

### QA
- [ ]  This branch has been deployed to staging and tested.

### CODE REVIEW

**Review by samullen — APPROVED** [review]

**Review by stwf — APPROVED** [review]

**Review by bmartin2015 — APPROVED** [review]

**Review by stwf — DISMISSED** [review]
Are we using travis for anything?

**Comment by hidnasio** [comment]
> Are we using travis for anything?

I think it's a legacy configuration file, I don't think we are running this on travis, do you want me to delete the file?

**Review by samullen — DISMISSED** [review]

**Comment by samullen** [comment]
Please delete it

**Review by bmartin2015 — APPROVED** [review]

**Comment by hidnasio** [comment]
Closing this PR in favor of #11

**Pull request closed without merging**
